### ISSUE TITLE
Clicking quickly between tabs closes tab

### ISSUE THREAD

**Issue by robminchin** [darioflute/sospex#24]
Clicking quickly on one tab and then on a second tab (if the first was clicked accidentally, for example) closes the second tab rather than switching to it

**Comment by darioflute** [comment]
This happens not because of a bug but because by touching the left part of the tab label, the tab is removed. A cross should indicate this possibility, but it disappeared on Mac-OSX after an update of Pyqt (it still works on Linux).

See: https://bugreports.qt.io/browse/QTBUG-61092
See also: https://github.com/spyder-ide/spyder/issues/5097

**Comment by darioflute** [comment]
When accidentally pressing the closing cross, a confirmation dialog appears to confirm the action.
